### ISSUE TITLE
Typo in Numpy and Pandas versions?

### ISSUE THREAD

**Issue by FiReTiTi** [mahmoodlab/MAPS#1]
Hi,
is there not a typo in the requested Numpy version?
Wouldn't it be 1.21.5 instead of 1.12.5?
Same for Pandas, version 1.5.5 does not exist (anymore?). Which one should we use?
Regards,

**Comment by FiReTiTi** [comment]
Btw, when installing mlxtend required version, it also forced the upgrade to numpy==1.26.4, which is also requested by scipy.

**Comment by m-shaban** [comment]
The inclusion of the >= operator in the requirment.txt file for the versions of each library allows users to choose any compatible version surpassing the specified minimum. I've recently reinstalled all libraries on my machine to ensure accuracy and found no inconsistencies in versioning. I highly advise adhering to the instructions provided in the readme file to set up your environment seamlessly.
