### ISSUE TITLE
Requirements.txt IPython

### ISSUE THREAD

**Issue by rharkes** [mahmoodlab/MAPS#2]
I got an error in
```
File "C:\Users\my\path\to\directory\lib\runpy.py", line 252, in _get_code_from_file
```
It was solved by installing IPython. (found the same error here: https://github.com/weecology/DeepForest/issues/406)

**Comment by m-shaban** [comment]
I think the IPython library is only required for model training using a Jupyter notebook. I have trained multiple models using the scripts given under [scripts/MAPS](https://github.com/mahmoodlab/MAPS/scripts/MAPS) without using this library. However, I have added this library to the requirment.txt file for completeness.
